### PR TITLE
Refactor docker compose

### PR DESCRIPTION
**Pull request by alypse**
express and react separated into /backend and /frontend respectively.

Readme updated to describe the dev process to start both locally. We can build the frontend and ship the build dir as static with express, express has a route to load static directories!

This is more of an architectural decision about how we ship/deploy, and I think we need to consider where the db will come in. 

Anyway, if you're happy with this structure, please merge!

### CODE REVIEW

**Comment by samiam109** [comment]
I like it. I think we should still have a Dockerfile for each at this point so we understand what the container looks like for each of the development domains.

Architecturally I agree it's probably over engineering the solution to deploy these as separate images, I'm curious if we can use docker compose to orchestrate the Dockerfiles into a single image for deployment.

**Comment by samiam109** [comment]
If we go the route of serving a static file with express then it definitely won't make sense to have these deployed into their own containers. However we do gain autonomy of deployment if these are separate E.g. deploy one when changes are available

**Review by samiam109 — COMMENTED** [review]
Left a few comments :)

**Comment by alypse** [comment]
Thanks Sam. 

I agree that we would probably lose the ability to deploy front end and backend atomically, but given the intended scope of this project, is serving FE with a distinct container potentially a 'YAGNI' requirement?

**Pull request merged**
